import Foundation

func check(_ condition: @autoclosure () -> Bool, _ message: String) {
    if !condition() { fatalError(message) }
}
check(TranscriptExport.clock(59.9996, milliseconds: true) == "00:01:00,000", "Milliseconds must carry into the next minute")
check(TranscriptExport.clock(3600.125, milliseconds: true) == "01:00:00,125", "Hour timestamps")
check(TranscriptExport.clock(-1) == "00:00:00", "Clamp negative timestamps")
let early = TranscriptLine(start: 0, end: 7, text: "確認句")
let tail = TranscriptLine(start: 7, end: 12, text: "尚未說完")
let live = WindowDecision.make(lines: [early, tail], samples: 12 * 16000, offset: 0, final: false)
check(live.confirmed == [early] && live.provisional == [tail], "Keep the unstable tail provisional")
check(live.consumed == 7 * 16000, "Advance only to the confirmed segment boundary")
let stopped = WindowDecision.make(lines: [tail], samples: 5 * 16000, offset: 7, final: true)
check(stopped.confirmed == [tail] && stopped.consumed == 5 * 16000, "Pause must flush short trailing speech")
let silence = WindowDecision.make(lines: [], samples: 12 * 16000, offset: 0, final: false)
check(silence.consumed == 10 * 16000, "Silence must progress while retaining right context")
let spanning = TranscriptLine(start: 40, end: 66, text: "很長的連續語句")
let full = WindowDecision.make(lines: [spanning], samples: 26 * 16000, offset: 40, final: false)
check(full.confirmed == [spanning] && full.consumed == 26 * 16000, "Long unsegmented speech must not stall")
let preview = WindowDecision.make(lines: [early], samples: 7 * 16000, offset: 0, final: false)
check(preview.consumed == 0 && preview.provisional == [early], "Short preview must not advance durable position")
let phrase = TranscriptLine(start: 0, end: 2, text: "中文 with CRISPR")
let agreement = WindowDecision.make(lines: [phrase], samples: 5 * 16000, offset: 0, final: false, previous: [phrase])
check(agreement.confirmed == [phrase] && agreement.consumed == 2 * 16000, "Repeated stable speech can confirm before twelve seconds")
let changed = TranscriptLine(start: 0, end: 2, text: "中文 with Cas9")
let disagreement = WindowDecision.make(lines: [changed], samples: 5 * 16000, offset: 0, final: false, previous: [phrase])
check(disagreement.consumed == 0, "A revised hypothesis must not be committed early")
let tooRecent = WindowDecision.make(lines: [phrase], samples: 3 * 16000, offset: 0, final: false, previous: [phrase])
check(tooRecent.consumed == 0, "Agreement must retain right context")
let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
let store = try SessionStore(root: directory)
var session = LectureSession(title: "中文 / English 課堂", model: "test", language: "auto")
session.lines = [TranscriptLine(start: 2.1, end: 3.25, text: "Hello 中文"), TranscriptLine(start: 0, end: 1, text: "開場")]
session.bookmarks = [Bookmark(seconds: 2, note: "重點")]
session.parts = [AudioPart(fileName: "test.pcm", offset: 0, sampleCount: 16000, processedSamples: 16000)]
try store.save(session)
// Simulate a crash after audio was persisted but before JSON was checkpointed.
try Data(repeating: 0, count: 32000 * 4).write(to: store.audioURL(session, session.parts[0]))
let recovered = try store.loadAll()[0]
check(recovered.parts[0].sampleCount == 32000, "Recovery must account for unsaved audio samples")
check(recovered.parts[0].processedSamples == 16000, "Recovery must retain last confirmed boundary")
check(recovered.hasPendingAudio, "Interrupted audio must be recoverable")
check(recovered.lines == session.lines, "UTF-8 transcript must survive persistence")
let srt = TranscriptExport.render(session, as: .srt)
check(srt.hasPrefix("1\n00:00:00,000 --> 00:00:01,000\n開場\n"), "SRT must sort segments and start numbering at one")
check(srt.contains("2\n00:00:02,100 --> 00:00:03,250\nHello 中文"), "SRT time and Unicode preservation")
check(!srt.contains("重點"), "Bookmarks must not create phantom subtitle cues")
check(TranscriptExport.render(recovered, as: .txt).contains("尚有音訊未完成"), "Incomplete export must be disclosed")
check(TranscriptExport.render(session, as: .markdown).contains("## 重點標記"), "Markdown bookmarks")
let exported = try store.export(session, format: .txt)
check(exported.deletingLastPathComponent() == store.folder(session.id), "Title must not escape export directory")
let exportedText = try String(contentsOf: exported, encoding: .utf8)
check(exportedText.contains("Hello 中文"), "Real exported file content")
let oldJSON = try JSONSerialization.jsonObject(with: JSONEncoder().encode(session)) as! [String: Any]
var legacy = oldJSON
legacy.removeValue(forKey: "vocabulary")
let oldSession = try JSONDecoder().decode(LectureSession.self, from: JSONSerialization.data(withJSONObject: legacy))
check(oldSession.vocabulary == nil, "Existing sessions without vocabulary must still open")
let neighbor = LectureSession(title: "保留的錄音", model: "test", language: "mixed", vocabulary: "Cas9")
try store.save(neighbor)
try store.delete(session.id)
check(!FileManager.default.fileExists(atPath: store.folder(session.id).path), "Deleting a session removes audio, JSON and local exports")
let remaining = try store.loadAll()
check(remaining.count == 1 && remaining[0].id == neighbor.id && remaining[0].vocabulary == "Cas9", "Deletion must preserve the other lecture and vocabulary")
try store.delete(session.id)
let outside = directory.appendingPathComponent("outside")
try FileManager.default.createDirectory(at: outside, withIntermediateDirectories: true)
let marker = outside.appendingPathComponent("keep.txt")
try Data("keep".utf8).write(to: marker)
let linkID = UUID()
try FileManager.default.createSymbolicLink(at: store.folder(linkID), withDestinationURL: outside)
var rejected = false
do { try store.delete(linkID) } catch { rejected = true }
check(rejected && FileManager.default.fileExists(atPath: marker.path), "Deletion must reject redirected session directories")
print("PASS: streaming agreement, legacy data, isolated deletion, timestamps, SRT, persistence and recovery")
